#!/bin/sh
mvn clean package && docker build -t kamlendupandey/SampleMicroerviceApp .
docker rm -f SampleMicroerviceApp 2>/dev/null || true && docker run -it --name SampleMicroerviceApp -p 8080:8080 -p 4848:4848 -p 8181:8181 --name SampleMicroerviceApp kamlendupandey/SampleMicroerviceApp
