#!/bin/sh
mvn clean package && docker build -t kamlendupandey/SampleClientApp .
docker rm -f SampleClientApp 2>/dev/null || true && docker run -it --name SampleClientApp -p 8080:8080 -p 4848:4848 -p 8181:8181 --name SampleClientApp kamlendupandey/SampleClientApp
